### ISSUE TITLE
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1

### ISSUE THREAD

**Issue by dwijenrudrapal** [medallia/Word2VecJava#21]
medallia-word2vec is showing error while i run the function searcher.
[cosineDistance("money", "Honey")]
Error comes like
Exception in thread "main" com.medallia.word2vec.Searcher$UnknownWordException: Unknown search word 'Honey'
    at com.medallia.word2vec.SearcherImpl.getVector(SearcherImpl.java:83)
    at com.medallia.word2vec.SearcherImpl.cosineDistance(SearcherImpl.java:45)
    at com.medallia.word2vec.Word2VecExamples.interact(Word2VecExamples.java:130)
    at com.medallia.word2vec.Word2VecExamples.demoWord(Word2VecExamples.java:73)
## BUILD FAILURE

Total time: 15.075s
Finished at: Fri May 22 13:26:27 IST 2015
## Final Memory: 5M/15M

Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (default-cli) on project medallia-word2vec: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException.

PLease i need kind help.

**Comment by guerda** [comment]
Hi 
As the error message says, your trained vocabulary does not contain the word "Honey". I think this depends on your text corpus and your training settings.

**Comment by guerda** [comment]
I think this is a duplicate of #13.

**Comment by dwijenrudrapal** [comment]
Thank u for your kind reply. If the word is not in vocabulary why "Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1" error comes?
Moreover, how can i handle this type of words rather printing errors? If word is not there, it should print status. Actually i am getting the link where i should do the changes.

**Comment by dwijenrudrapal** [comment]
@guerda you are right, issue is duplicate of #13. I am trying to overcome since last few days. But could not. In other cases system is working fine.

**Comment by guerda** [comment]
@dwijenrudrapal It depends, how you call the maven target. It seems that you use mvn execute, which will listen to the exit code of the Java class. As the UnknownWordException is thrown and not catched, it will set the exit code to non-zero. Therefore, the Maven execute will say that the command failed.

I recommend to include the word2vecjava library in an Eclipse or a Netbeans project and write your own code to include the calls. Then you can catch the UnknownWordException and output the status.

**Comment by dwijenrudrapal** [comment]
based on my English text data i edited the code to handle the errors for non-vocabulary words. I found the implementation works fine for English text only. When i try to train the system for Bengali text, system is not compatible.  Its printing ? for each Bengali characters in the train file. Can you kindly help me on this issue?

**Comment by dwijenrudrapal** [comment]
based on my English text data i edited the code to handle the errors for
non-vocabulary words. I found the implementation works fine for English
text only. When i try to train the system for Bengali text, system is not
compatible. Its printing ? for each Bengali characters in the train file.
Can you kindly help me on this issue?

**Comment by guerda** [comment]
Are you using a working UTF-8 console to print the words? Arabic text works fine with Word2VecJava, see https://github.com/guerda/Word2VecJava/blob/bug-arabic-text/src/test/java/com/medallia/word2vec/Word2VecTest.java#L179
I suspect you are printing the words with an incorrect encoding.

**Comment by dwijenrudrapal** [comment]
Finally I managed to work your implementation for Bengali Language. Both
Write and read function i little modified. I used "UTF-8" as an argument in
these functions. So files are opening in and writing to in desired script.
One important observation is that, for two Bengali words i am getting
cosine distance more than 1 (like 1.65874), which is not expected. Cosine
distance must be 0-1. So, while i am calculating sentence level similarity,
score is coming more than 1. Working on this issue.
I hope, You know Bengali is one major language in India. I am doing
research on Bengali language. I hope, I will get your kind help from you in
future also.

Regards
Dwijen

**Comment by guerda** [comment]
Good that this could be resolved. About the cosine distance larger than 1: can you provide a test case, where this happens? So we can reproduce this error and hopefully fix it. A new issue would be suitable for this.
I would suggest to close this issue, as your initial problem seems to be fixed, OK?
