### ISSUE TITLE
Java Heap space error

### ISSUE THREAD

**Issue by AbhiMangal** [medallia/Word2VecJava#33]
Sir Please tell me when i am increase the size of file dataset  which  i want to use for training neural network. then i am facing the exception : 
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at java.lang.String.substring(String.java:1956)
    at java.lang.String.split(String.java:2340)
    at java.lang.String.split(String.java:2409)
    at word2vector.Word2VecExamples$1.apply(Word2VecExamples.java:51)
    at word2vector.Word2VecExamples$1.apply(Word2VecExamples.java:48)
    at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:617)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
    at com.google.common.collect.Iterators$5.hasNext(Iterators.java:548)
    at word2vector.Word2VecTrainer.count(Word2VecTrainer.java:43)
    at word2vector.Word2VecTrainer.train(Word2VecTrainer.java:77)
    at word2vector.Word2VecTrainerBuilder.train(Word2VecTrainerBuilder.java:243)
    at word2vector.Word2VecExamples.demoWord(Word2VecExamples.java:69)
    at word2vector.Word2VecExamples.main(Word2VecExamples.java:36)

please tell me what should i am doing to remove this error.

**Comment by guerda** [comment]
Try to Google Java OutOfMemory error.

**Comment by AbhiMangal** [comment]
thanks..

**Comment by AbhiMangal** [comment]
sir how can i reduce the time to train the neural network . when i use very big file to train the model?
please reply me as soon as possible.

**Comment by AbhiMangal** [comment]
thanks.

On Fri, Nov 20, 2015 at 1:17 AM, Philip Gillißen <notifications@github.com>
wrote:

> Try to Google Java OutOfMemory error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/medallia/Word2VecJava/issues/33#issuecomment-158173990>
> .
>



-- 
Thanks & Regrads
Abhilasha Mangal
(Software Engineer)
Information Technology
B.tech

**Comment by guerda** [comment]
Try increasing fast memory and add additional CPUs. This will increase performance of the training.

**Comment by AbhiMangal** [comment]
may i use for it multithreading.?

**Comment by guerda** [comment]
This word2vec implementation uses multi threading wherever possible. You can configure how many threads are used.

**Comment by XiyunLiu** [comment]
How large the file you are training on? I am facing the same issue. I think the iterator should help save a lot of memory, but not.
